version: '3.8'

services:
  db:
    build:
      context: ./database  # Usa la carpeta donde está el Dockerfile de MySQL
      dockerfile: Dockerfile  # Asegura que Docker use el Dockerfile personalizado
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: andaluciaskills
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql  # Volumen para persistencia de datos
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./andaluciaskills
      dockerfile: Dockerfile
    container_name: spring_boot_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: andaluciaskills
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/andaluciaskills?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SERVER_PORT: 8080
      JWT_SECRET: K3lF7QAspsGG09mbIaryP3jtRkkxC5pwTV6BtM4kU5EXYRDEkMM9dUdjlpjPrEWYM
      JWT_EXPIRATION: 86400000
      SPRING_MVC_CONTENTNEGOTIATION_FAVOR_PARAMETER: "true"
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG
      LOGGING_LEVEL_COM_EXAMPLE_ANDALUCIASKILLS: DEBUG

  frontend:
    build:
      context: ./competicion
      dockerfile: Dockerfile
    container_name: angular_app
    ports:
      - "4200:4200"
    environment:
      BACKEND_URL: "http://localhost:8080"  
    volumes:
      - ./competicion:/app

volumes:
  db_data: {}  # Define el volumen 'db_data'
